# Generated by Django 3.0.7 on 2021-11-28 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='down_votes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='release_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='review',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='up_votes',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
