# Generated by Django 3.0.7 on 2021-11-28 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_auto_20211128_0331'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
